name= "Samad"
age=11
weight=32.6
print("name :",name)
print("Data type of name is", type (name))
print("Age :", age)
print ("data type of age is" ,(age))
print("weight :", weight)
print  ("data type of weight is", (weight))
print("/n after type casting....")
age= str(age)
print(age)
print("data type of age is", type (age))
weight=int(weight)
print(weight)
print ("data type of weight is", type (weight))